### ISSUE TITLE
Wrong wget options

### ISSUE THREAD

**Issue by giviz** [site24x7/ansible-site24x7#1]
```
 - name: Download 64 bit Site24x7 agent from public URL
   shell: wget -r https://staticdownloads.site24x7.com/server/Site24x7_Linux_64bit.install
   when: ansible_machine == "x86_64"
```

wget -r make no sense here as you get : 
# ls -al staticdownloads.site24x7.com/server/Site24x7_Linux_64bit.install

-rw-r--r-- 1 root root 7884199 Aug  5 13:05 staticdownloads.site24x7.com/server/Site24x7_Linux_64bit.install

But on the next command, you change the rights on the file on the current directory : 

```
 - name: Change permission of the downloaded 64 bit install file
   file: path=Site24x7_Linux_64bit.install mode=0755
```

You can either do a "wget" without "-r" or change the path in the second command.

Also, you playbook doesn't remove the Site24x7_Linux_64bit.install after execution.

**Comment by site24x7-old** [comment]
Hi giviz,

Thanks for the suggestions and apologies for the delayed response.

We have fixed the 'wget' option and installer file will be deleted after the execution of playbook.
